#!/bin/bash

# Usage: extract filename 
# extract filename dir to extract to specific dir

archive=`readlink -f "$1"`
ext=`echo "$1"|awk -F . '{print $NF}'`

if [ $# -lt 2 ]
	then
	extractdir=`basename $1 .$ext`
	extractdir=./`basename $extractdir .tar` # fix for .tar.something
	echo "Extracting to: $extractdir"
else
	extractdir="$2"

	extractdir=`readlink -f "$extractdir"`
	echo $extractdir
fi

if   [ "$ext" = "zip" ]
	then
	unzip "$archive" -d "$extractdir"

elif [ "$ext" = "rar" ]
	then

	if [ ! -d "$extractdir" ]
		then
		mkdir "$extractdir"
	fi
	
	cd "$extractdir"	
	unrar x "$archive"

# If file is .tar.something
elif [ `echo "$1" | awk -F . '{print $(NF-1)}'` = "tar" ]
	then
		dirmade=false
		if [ ! -d "$extractdir" ]
			then
			mkdir "$extractdir"
			dirmade=true
		fi
		
		if [ "$ext" = "gz" ]
			then
			tar xvzf "$archive" -C "$extractdir"

		elif [ "$ext" = "bz2" ]
			then
			tar xvjf "$archive" -C "$extractdir"
		
		# If it couldnt extract, remove the folder
		elif [ $dirmade = true ]
			then
			rmdir $extractdir
		fi
	
fi
